### ISSUE TITLE
Missing Model

### ISSUE THREAD

**Issue by melandur** [Jpvmello/type-identification-mri-sequences#1]
Hi Jpvmello, great work, congrats!

Isn't there a  bt5_sl4.pth model for the resnet18, which works with 5 classes [T1, T2, T1c, Flair, Others]?
I see only the bt4_sl4.pth model on google drive.
Thanks in advanced!

**Comment by Jpvmello** [comment]
Thanks! As the paper is not published yet, I agree I should have been a bit clearer in the models description. In the paper we refer to BRATS+TCGA5 as the "main dataset". Thus, the models trained with this dataset were referrered as main_slX.pth. In other words, the model "bt5_sl4.pth" you are looking for is the model "main_sl4.pth" on drive.

**Comment by melandur** [comment]
Thanks!
Appreciate the fast response!
